name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Run Code Quality Check
        run: npm run lint

      - name: Run Automated Tests
        run: npm test

      - name: Build Docker Image
        run: docker build -t cicdproject:v1 .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag cicdproject:v1 gurramrahul/cicdproject:v1
          docker tag cicdproject:v1 gurramrahul/cicdproject:latest

      - name: Push Docker Images
        run: |
          docker push gurramrahul/cicdproject:v1
          docker push gurramrahul/cicdproject:latest

  deploy-development:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Development
        run: |
          echo "Deploying application to Development Environment"

  deploy-production:
    needs: deploy-development
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Deploy to Production
        run: |
          echo "Production Deployment Approved"
          echo "Deploying application to Production Environment"
